## The source repositories and target repositories are one-to-one correspondence.
sourceRepos:
  - registry: open-telemetry/opentelemetry-operator
    name: opentelemetry-operator
    host: ghcr.io
  - registry: kubebuilder
    name: kube-rbac-proxy
    host: gcr.io

targetRepos:
  - registry: public.ecr.aws/y5j3l8r7
    name: adot-operator
  - registry: public.ecr.aws/y5j3l8r7
    name: mirror-kube-rbac-proxy
